# Top-level convenience Makefile
# Usage (from OpenWrt buildroot):
#   make package/tieba-sign/compile
#   make package/luci-app-tieba-sign/compile

.PHONY: all clean

all:
	@echo "Add this directory to your OpenWrt feeds.conf, then:"
	@echo "  ./scripts/feeds update tieba-sign"
	@echo "  ./scripts/feeds install tieba-sign luci-app-tieba-sign"
	@echo "  make menuconfig  # select under LuCI -> Applications"
	@echo "  make package/tieba-sign/compile"
	@echo "  make package/luci-app-tieba-sign/compile"
